# Generated by Django 2.1.5 on 2019-02-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=200)),
                ('mnb2pred', models.CharField(max_length=4)),
                ('rfpred', models.CharField(max_length=4)),
                ('decisionpred', models.CharField(max_length=4)),
                ('svmpred', models.CharField(max_length=4)),
                ('knnpred', models.CharField(max_length=4)),
                ('hybrid', models.CharField(max_length=4)),
                ('predicted_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
